# Generated by Django 4.2.6 on 2023-10-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_photo'),
        ('activities', '0002_alter_activity_accounts_registrations_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivityLikes',
            new_name='ActivityLike',
        ),
    ]
