# Generated by Django 4.2.6 on 2023-10-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='accounts_registrations',
            new_name='registred_accounts',
        ),
        migrations.RemoveField(
            model_name='activityregistration',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='activityregistration',
            name='status',
            field=models.CharField(null=False,blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending',max_length=8),
        ),
    ]
