# Generated by Django 4.2.6 on 2023-10-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_rename_accounts_registrations_activity_registred_accounts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
