# Generated by Django 4.2.6 on 2023-10-28 12:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinClubForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('how_found_us', models.CharField(max_length=255)),
                ('reasons', models.CharField(max_length=255)),
                ('goals', models.TextField(max_length=1024)),
                ('receive_emails', models.BooleanField(blank=True, default=False)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=8)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='join_club_form', to='accounts.account')),
            ],
        ),
    ]
